# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ma/streaming/key_generator/v1/key_generator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ma/streaming/key_generator/v1/key_generator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1ma/streaming/key_generator/v1/key_generator.proto\x12\x1dma.streaming.key_generator.v1\"P\n\x18GenerateUniqueKeyRequest\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32&.ma.streaming.key_generator.v1.KeyType\"M\n\x19GenerateUniqueKeyResponse\x12\x14\n\nstring_key\x18\x01 \x01(\tH\x00\x12\x13\n\tulong_key\x18\x02 \x01(\x04H\x00\x42\x05\n\x03key*L\n\x07KeyType\x12\x18\n\x14KEY_TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0eKEY_TYPE_ULONG\x10\x01\x12\x13\n\x0fKEY_TYPE_STRING\x10\x02\x32\xa4\x01\n\x19UniqueKeyGeneratorService\x12\x86\x01\n\x11GenerateUniqueKey\x12\x37.ma.streaming.key_generator.v1.GenerateUniqueKeyRequest\x1a\x38.ma.streaming.key_generator.v1.GenerateUniqueKeyResponseB\x1eH\x03\xaa\x02\x19MA.Streaming.KeyGeneratorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ma.streaming.key_generator.v1.key_generator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003\252\002\031MA.Streaming.KeyGenerator'
  _globals['_KEYTYPE']._serialized_start=245
  _globals['_KEYTYPE']._serialized_end=321
  _globals['_GENERATEUNIQUEKEYREQUEST']._serialized_start=84
  _globals['_GENERATEUNIQUEKEYREQUEST']._serialized_end=164
  _globals['_GENERATEUNIQUEKEYRESPONSE']._serialized_start=166
  _globals['_GENERATEUNIQUEKEYRESPONSE']._serialized_end=243
  _globals['_UNIQUEKEYGENERATORSERVICE']._serialized_start=324
  _globals['_UNIQUEKEYGENERATORSERVICE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
