# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ma.streaming.key_generator.v1 import key_generator_pb2 as ma_dot_streaming_dot_key__generator_dot_v1_dot_key__generator__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ma/streaming/key_generator/v1/key_generator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UniqueKeyGeneratorServiceStub(object):
    """Unique key generator service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateUniqueKey = channel.unary_unary(
                '/ma.streaming.key_generator.v1.UniqueKeyGeneratorService/GenerateUniqueKey',
                request_serializer=ma_dot_streaming_dot_key__generator_dot_v1_dot_key__generator__pb2.GenerateUniqueKeyRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_key__generator_dot_v1_dot_key__generator__pb2.GenerateUniqueKeyResponse.FromString,
                _registered_method=True)


class UniqueKeyGeneratorServiceServicer(object):
    """Unique key generator service
    """

    def GenerateUniqueKey(self, request, context):
        """Generate a unique key which can be used to uniquely identify entities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UniqueKeyGeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateUniqueKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateUniqueKey,
                    request_deserializer=ma_dot_streaming_dot_key__generator_dot_v1_dot_key__generator__pb2.GenerateUniqueKeyRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_key__generator_dot_v1_dot_key__generator__pb2.GenerateUniqueKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ma.streaming.key_generator.v1.UniqueKeyGeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ma.streaming.key_generator.v1.UniqueKeyGeneratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UniqueKeyGeneratorService(object):
    """Unique key generator service
    """

    @staticmethod
    def GenerateUniqueKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.key_generator.v1.UniqueKeyGeneratorService/GenerateUniqueKey',
            ma_dot_streaming_dot_key__generator_dot_v1_dot_key__generator__pb2.GenerateUniqueKeyRequest.SerializeToString,
            ma_dot_streaming_dot_key__generator_dot_v1_dot_key__generator__pb2.GenerateUniqueKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
