# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ma.streaming.api.v1 import api_pb2 as ma_dot_streaming_dot_api_dot_v1_dot_api__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ma/streaming/api/v1/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PacketWriterServiceStub(object):
    """Packet writer service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteDataPacket = channel.unary_unary(
                '/ma.streaming.api.v1.PacketWriterService/WriteDataPacket',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketResponse.FromString,
                _registered_method=True)
        self.WriteDataPackets = channel.stream_unary(
                '/ma.streaming.api.v1.PacketWriterService/WriteDataPackets',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketsRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketsResponse.FromString,
                _registered_method=True)
        self.WriteInfoPacket = channel.unary_unary(
                '/ma.streaming.api.v1.PacketWriterService/WriteInfoPacket',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketResponse.FromString,
                _registered_method=True)
        self.WriteInfoPackets = channel.stream_unary(
                '/ma.streaming.api.v1.PacketWriterService/WriteInfoPackets',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketsRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketsResponse.FromString,
                _registered_method=True)


class PacketWriterServiceServicer(object):
    """Packet writer service.
    """

    def WriteDataPacket(self, request, context):
        """Write a packet for a specified data source
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteDataPackets(self, request_iterator, context):
        """Continuously write a stream of data packets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteInfoPacket(self, request, context):
        """Write an info packet of a specified type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteInfoPackets(self, request_iterator, context):
        """Continuously write a stream of info packets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PacketWriterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteDataPacket': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteDataPacket,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketResponse.SerializeToString,
            ),
            'WriteDataPackets': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteDataPackets,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketsRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketsResponse.SerializeToString,
            ),
            'WriteInfoPacket': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteInfoPacket,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketResponse.SerializeToString,
            ),
            'WriteInfoPackets': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteInfoPackets,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketsRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ma.streaming.api.v1.PacketWriterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ma.streaming.api.v1.PacketWriterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PacketWriterService(object):
    """Packet writer service.
    """

    @staticmethod
    def WriteDataPacket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.PacketWriterService/WriteDataPacket',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteDataPackets(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ma.streaming.api.v1.PacketWriterService/WriteDataPackets',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketsRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteDataPacketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteInfoPacket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.PacketWriterService/WriteInfoPacket',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteInfoPackets(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ma.streaming.api.v1.PacketWriterService/WriteInfoPackets',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketsRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.WriteInfoPacketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataFormatManagerServiceStub(object):
    """Data format manager service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetParameterDataFormatId = channel.unary_unary(
                '/ma.streaming.api.v1.DataFormatManagerService/GetParameterDataFormatId',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParameterDataFormatIdRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParameterDataFormatIdResponse.FromString,
                _registered_method=True)
        self.GetEventDataFormatId = channel.unary_unary(
                '/ma.streaming.api.v1.DataFormatManagerService/GetEventDataFormatId',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventDataFormatIdRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventDataFormatIdResponse.FromString,
                _registered_method=True)
        self.GetParametersList = channel.unary_unary(
                '/ma.streaming.api.v1.DataFormatManagerService/GetParametersList',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParametersListRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParametersListResponse.FromString,
                _registered_method=True)
        self.GetEvent = channel.unary_unary(
                '/ma.streaming.api.v1.DataFormatManagerService/GetEvent',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventResponse.FromString,
                _registered_method=True)


class DataFormatManagerServiceServicer(object):
    """Data format manager service
    """

    def GetParameterDataFormatId(self, request, context):
        """Request a data format ID for a set of parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventDataFormatId(self, request, context):
        """Request a data format ID for an event
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParametersList(self, request, context):
        """Request a list of paramters for a given data format ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvent(self, request, context):
        """Request an event for a given data format ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataFormatManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetParameterDataFormatId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameterDataFormatId,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParameterDataFormatIdRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParameterDataFormatIdResponse.SerializeToString,
            ),
            'GetEventDataFormatId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventDataFormatId,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventDataFormatIdRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventDataFormatIdResponse.SerializeToString,
            ),
            'GetParametersList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParametersList,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParametersListRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParametersListResponse.SerializeToString,
            ),
            'GetEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvent,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ma.streaming.api.v1.DataFormatManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ma.streaming.api.v1.DataFormatManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataFormatManagerService(object):
    """Data format manager service
    """

    @staticmethod
    def GetParameterDataFormatId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.DataFormatManagerService/GetParameterDataFormatId',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParameterDataFormatIdRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParameterDataFormatIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventDataFormatId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.DataFormatManagerService/GetEventDataFormatId',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventDataFormatIdRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventDataFormatIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParametersList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.DataFormatManagerService/GetParametersList',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParametersListRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetParametersListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.DataFormatManagerService/GetEvent',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConnectionManagerServiceStub(object):
    """////////////////////////////////////
    		Connection Section			//
    ////////////////////////////////////

    Connection manager service
    Open and close Connections
    Connections maintain the current offset position
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewConnection = channel.unary_unary(
                '/ma.streaming.api.v1.ConnectionManagerService/NewConnection',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.NewConnectionRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.NewConnectionResponse.FromString,
                _registered_method=True)
        self.GetConnection = channel.unary_unary(
                '/ma.streaming.api.v1.ConnectionManagerService/GetConnection',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetConnectionRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetConnectionResponse.FromString,
                _registered_method=True)
        self.CloseConnection = channel.unary_unary(
                '/ma.streaming.api.v1.ConnectionManagerService/CloseConnection',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CloseConnectionRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CloseConnectionResponse.FromString,
                _registered_method=True)


class ConnectionManagerServiceServicer(object):
    """////////////////////////////////////
    		Connection Section			//
    ////////////////////////////////////

    Connection manager service
    Open and close Connections
    Connections maintain the current offset position
    """

    def NewConnection(self, request, context):
        """Create a new connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnection(self, request, context):
        """Get an existing connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseConnection(self, request, context):
        """Close connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectionManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.NewConnection,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.NewConnectionRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.NewConnectionResponse.SerializeToString,
            ),
            'GetConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnection,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetConnectionRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetConnectionResponse.SerializeToString,
            ),
            'CloseConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseConnection,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CloseConnectionRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CloseConnectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ma.streaming.api.v1.ConnectionManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ma.streaming.api.v1.ConnectionManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConnectionManagerService(object):
    """////////////////////////////////////
    		Connection Section			//
    ////////////////////////////////////

    Connection manager service
    Open and close Connections
    Connections maintain the current offset position
    """

    @staticmethod
    def NewConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.ConnectionManagerService/NewConnection',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.NewConnectionRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.NewConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.ConnectionManagerService/GetConnection',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetConnectionRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.ConnectionManagerService/CloseConnection',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CloseConnectionRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CloseConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PacketReaderServiceStub(object):
    """////////////////////////////////////
    		Packet Reader Section		//
    ////////////////////////////////////

    Read packets
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadPackets = channel.unary_stream(
                '/ma.streaming.api.v1.PacketReaderService/ReadPackets',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadPacketsRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadPacketsResponse.FromString,
                _registered_method=True)
        self.ReadEssentials = channel.unary_stream(
                '/ma.streaming.api.v1.PacketReaderService/ReadEssentials',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadEssentialsRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadEssentialsResponse.FromString,
                _registered_method=True)
        self.ReadDataPackets = channel.unary_stream(
                '/ma.streaming.api.v1.PacketReaderService/ReadDataPackets',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadDataPacketsRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadDataPacketsResponse.FromString,
                _registered_method=True)


class PacketReaderServiceServicer(object):
    """////////////////////////////////////
    		Packet Reader Section		//
    ////////////////////////////////////

    Read packets
    """

    def ReadPackets(self, request, context):
        """Continuously read all packets from the specified connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadEssentials(self, request, context):
        """Continuously read all of the essential packets from this connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDataPackets(self, request, context):
        """Continuously read all data packets containing any of the specified parameters or events
        Only data packets will be returned (i.e. no config, metadata etc)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PacketReaderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadPackets': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadPackets,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadPacketsRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadPacketsResponse.SerializeToString,
            ),
            'ReadEssentials': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadEssentials,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadEssentialsRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadEssentialsResponse.SerializeToString,
            ),
            'ReadDataPackets': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadDataPackets,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadDataPacketsRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadDataPacketsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ma.streaming.api.v1.PacketReaderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ma.streaming.api.v1.PacketReaderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PacketReaderService(object):
    """////////////////////////////////////
    		Packet Reader Section		//
    ////////////////////////////////////

    Read packets
    """

    @staticmethod
    def ReadPackets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ma.streaming.api.v1.PacketReaderService/ReadPackets',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadPacketsRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadPacketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadEssentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ma.streaming.api.v1.PacketReaderService/ReadEssentials',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadEssentialsRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadEssentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDataPackets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ma.streaming.api.v1.PacketReaderService/ReadDataPackets',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadDataPacketsRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.ReadDataPacketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SessionManagementServiceStub(object):
    """////////////////////////////////////////
    		Session Management Section		//
    ////////////////////////////////////////

    Manage sessions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/ma.streaming.api.v1.SessionManagementService/CreateSession',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/ma.streaming.api.v1.SessionManagementService/EndSession',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.EndSessionResponse.FromString,
                _registered_method=True)
        self.GetCurrentSessions = channel.unary_unary(
                '/ma.streaming.api.v1.SessionManagementService/GetCurrentSessions',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetCurrentSessionsRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetCurrentSessionsResponse.FromString,
                _registered_method=True)
        self.GetSessionInfo = channel.unary_unary(
                '/ma.streaming.api.v1.SessionManagementService/GetSessionInfo',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionInfoRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionInfoResponse.FromString,
                _registered_method=True)
        self.GetSessionStartNotification = channel.unary_stream(
                '/ma.streaming.api.v1.SessionManagementService/GetSessionStartNotification',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStartNotificationRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStartNotificationResponse.FromString,
                _registered_method=True)
        self.GetSessionStopNotification = channel.unary_stream(
                '/ma.streaming.api.v1.SessionManagementService/GetSessionStopNotification',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStopNotificationRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStopNotificationResponse.FromString,
                _registered_method=True)
        self.UpdateSessionIdentifier = channel.unary_unary(
                '/ma.streaming.api.v1.SessionManagementService/UpdateSessionIdentifier',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionIdentifierRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionIdentifierResponse.FromString,
                _registered_method=True)
        self.AddAssociateSession = channel.unary_unary(
                '/ma.streaming.api.v1.SessionManagementService/AddAssociateSession',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.AddAssociateSessionRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.AddAssociateSessionResponse.FromString,
                _registered_method=True)
        self.UpdateSessionDetails = channel.unary_unary(
                '/ma.streaming.api.v1.SessionManagementService/UpdateSessionDetails',
                request_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionDetailsRequest.SerializeToString,
                response_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionDetailsResponse.FromString,
                _registered_method=True)


class SessionManagementServiceServicer(object):
    """////////////////////////////////////////
    		Session Management Section		//
    ////////////////////////////////////////

    Manage sessions
    """

    def CreateSession(self, request, context):
        """Create a new session. Returns the unique session key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """End the session for a given unique session key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentSessions(self, request, context):
        """Get a list of the current sessions within the broker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionInfo(self, request, context):
        """Get the info for a session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionStartNotification(self, request, context):
        """Continuously notifies the client when a session starts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionStopNotification(self, request, context):
        """Continuously notifies the client when a session ends
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSessionIdentifier(self, request, context):
        """Update the session identifier given its unique session key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAssociateSession(self, request, context):
        """Add associate session to a session given its unique session key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSessionDetails(self, request, context):
        """Update the session details for a session given its unique session key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CreateSessionRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CreateSessionResponse.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.EndSessionRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.EndSessionResponse.SerializeToString,
            ),
            'GetCurrentSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentSessions,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetCurrentSessionsRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetCurrentSessionsResponse.SerializeToString,
            ),
            'GetSessionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionInfo,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionInfoRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionInfoResponse.SerializeToString,
            ),
            'GetSessionStartNotification': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSessionStartNotification,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStartNotificationRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStartNotificationResponse.SerializeToString,
            ),
            'GetSessionStopNotification': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSessionStopNotification,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStopNotificationRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStopNotificationResponse.SerializeToString,
            ),
            'UpdateSessionIdentifier': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSessionIdentifier,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionIdentifierRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionIdentifierResponse.SerializeToString,
            ),
            'AddAssociateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAssociateSession,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.AddAssociateSessionRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.AddAssociateSessionResponse.SerializeToString,
            ),
            'UpdateSessionDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSessionDetails,
                    request_deserializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionDetailsRequest.FromString,
                    response_serializer=ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ma.streaming.api.v1.SessionManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ma.streaming.api.v1.SessionManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionManagementService(object):
    """////////////////////////////////////////
    		Session Management Section		//
    ////////////////////////////////////////

    Manage sessions
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.SessionManagementService/CreateSession',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CreateSessionRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.SessionManagementService/EndSession',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.EndSessionRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.SessionManagementService/GetCurrentSessions',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetCurrentSessionsRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetCurrentSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.SessionManagementService/GetSessionInfo',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionInfoRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionStartNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ma.streaming.api.v1.SessionManagementService/GetSessionStartNotification',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStartNotificationRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStartNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionStopNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ma.streaming.api.v1.SessionManagementService/GetSessionStopNotification',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStopNotificationRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.GetSessionStopNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSessionIdentifier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.SessionManagementService/UpdateSessionIdentifier',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionIdentifierRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionIdentifierResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAssociateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.SessionManagementService/AddAssociateSession',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.AddAssociateSessionRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.AddAssociateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSessionDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ma.streaming.api.v1.SessionManagementService/UpdateSessionDetails',
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionDetailsRequest.SerializeToString,
            ma_dot_streaming_dot_api_dot_v1_dot_api__pb2.UpdateSessionDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
